# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simple.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simple.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csimple.proto\x12\x06simple\"C\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"I\n\x0fReceiptResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\t2M\n\x0cOrderService\x12=\n\x0cProcessOrder\x12\x14.simple.OrderRequest\x1a\x17.simple.ReceiptResponseB\nZ\x08./simpleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./simple'
  _globals['_ORDERREQUEST']._serialized_start=24
  _globals['_ORDERREQUEST']._serialized_end=91
  _globals['_RECEIPTRESPONSE']._serialized_start=93
  _globals['_RECEIPTRESPONSE']._serialized_end=166
  _globals['_ORDERSERVICE']._serialized_start=168
  _globals['_ORDERSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
